aperturebase/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.urls import path
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$',views.home,name='homeurl'),
    url(r'^articles/', include('articles.urls'), name='articlesurl'),
    url(r'^summernote/', include('django_summernote.urls')),
    url(r'^cats/',include('cats.urls'), name='catsurl'),
    
   

]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

articles/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.urls import path
from . import views


app_name = 'articles'

urlpatterns = [
    url(r'^$',views.article_list,name='list'),
    url(r'^(?P<slug>[\w-]+)/$',views.article_detail,name='detail'),
]

cats/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.urls import path
from . import views

app_name = 'cats'

urlpatterns = [

     url(r'^(?P<CatHead>[\w-]+)/$',views.cat, name='categories')
    
]

articles/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here
class Articles(models.Model):
    title = models.CharField(max_length=100)
    body = models.TextField()
    slug = models.SlugField(null=True)
    date = models.DateTimeField(auto_now_add=True)
    thumb = models.ImageField(default='skate.jpg',blank=True)
    img0 = models.ImageField(default='default.png', blank=True)
    img0cap = models.CharField(max_length=500, default='caption')
    img1 = models.ImageField(default = 'default.png',blank=True)
    img1cap = models.CharField(max_length=500, default='caption')
    img2 = models.ImageField(default='default.png', blank=True)
    img2cap = models.CharField(max_length=500,default='caption')
    img3 = models.ImageField(default='default.png', blank=True)
    img3cap = models.CharField(max_length=500,default='caption')
    img4 = models.ImageField(default='default.png', blank=True)
    img4cap = models.CharField(max_length=500,default='caption')
    img5 = models.ImageField(default='default.png', blank=True)
    img5cap = models.CharField(max_length=500,default='caption')
    img6 = models.ImageField(default='default.png', blank=True)
    img6cap = models.CharField(max_length=500,default='caption')
    img7 = models.ImageField(default='default.png', blank=True)
    img7cap = models.CharField(max_length=500,default='caption')
    img8 = models.ImageField(default='default.png', blank=True)
    img8cap = models.CharField(max_length=500,default='caption')
    img9 = models.ImageField(default='default.png', blank=True)
    img9cap = models.CharField(max_length=500,default='caption')



    def __str__(self):
        return self.title

    def snippet(self):
        return self.body[:50]

    

class Message(models.Model):
    name = models.CharField(max_length=100)
    sender = models.CharField(max_length=500)
    subject = models.CharField(max_length=500)
    message = models.TextField()

    def __str__(self):
        return self.name


class Cat(models.Model):
    CatHead = models.CharField(max_length=100,null=True)
    Thumb = models.ImageField(default = 'default.png',blank=True)
    

    def __str__(self):
        return self.CatHead
       

labels = ['im0','im1','im2','im3','im4','im5','im6','im7','im8','im9']
for i in labels:
    Cat.add_to_class(i, models.ImageField(default='default.png',blank=True))
    Cat.add_to_class(i+'_setting',models.TextField(null=True, blank=True))
    Cat.add_to_class(i+'_head',models.CharField(max_length=500,blank=True))

cats/models.py
from django.db import models

# Create your models here.

aperturebase/forms.py
from django import forms

class ContactForM(forms.Form):
    Name = forms.CharField(label='Name',max_length=100)
    sender = forms.EmailField(label='Email')
    
    subject = forms.CharField(max_length=100)
    message = forms.CharField(widget=forms.Textarea)

aperturebase/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from .forms import ContactForM
from django.core.mail import send_mail
from django.contrib import messages

from articles.models import Message, Cat


def home(request):
        #return HttpResponse('hey buddy you\'re at home')

        Cats = Cat.objects.all()
        

        if request.method == "POST":
                form = ContactForM(request.POST)
                if form.is_valid():
                        name = form.cleaned_data['Name']
                        email = form.cleaned_data['sender']
                        
                        subject = form.cleaned_data['subject']
                        message = form.cleaned_data['message']
                        

                        mess = Message()

                        mess.name = name
                        mess.sender = email
                        mess.subject = subject
                        mess.message = message

                        mess.save()
                        
                        messages.success(request,'Message sent')
                        return HttpResponseRedirect('/#message')

        else:
                form = ContactForM()


        
        return render(request, 'home.html',{'form':form,'Cats':Cats})

articles/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Articles
from django.urls import reverse

# Create your views here.
def article_list(request):
    article = Articles.objects.all().order_by('date')
    return render(request, 'articles/article_list.html',{'article':article})

def article_detail(request,slug):
    art1 = Articles.objects.get(slug=slug)
    body = art1.body
    
    di = ['img0','img1','img2','img3','img4','img5','img6','img7','img8','img9']

    
    for i in di:

        a = body.find('!! '+i+" !!")
        #exec('art1.'+body[a+3:a+8]+'.url')
        if(a!=-1):
            b = getattr(art1,i).url
            c =  getattr(art1, i+'cap')
            if(body[a+11:a+14]=="por"):

                

                body = body[:a] + "</p><div class='text-center ' style='margin-left:50px;margin-right:50px;margin-top:1em;margin-bottom:1em;'><img src=" + "'" +b+"'"+" class='img-fluid sizer-por' style='margin: 5 auto;'/><div class='text-center cap'><br><i>"+c+"</i></div></div><p>"+body[a+15:len(body)]
            else:

                body = body[:a] + "</p><div class='text-center ' style='margin-left:50px;margin-right:50px;margin-top:1em;margin-bottom:1em;'><img src=" + "'" +b+"'"+" class='img-fluid sizer ' style='margin: 5 auto;'/><div class='text-center cap'><br><i>"+c+"</i></div></div><p>"+body[a+10:len(body)] 
        else:
            pass
    rev_url = reverse('articles:detail',kwargs={'slug': art1.slug})
    homeurl = 'www.apertureminimus.tk'

    Allobj = Articles.objects.all()
    for i in range(len(Allobj)):
        if(Allobj[i].slug == art1.slug):
            currentpos = i
            if(i == len(Allobj)-1):
                prevobj = Allobj[i-1].slug
                nextobj = prevobj
            elif(i == 0):
                nextobj = Allobj[i+1].slug
                prevobj = nextobj
            else:
                nextobj = Allobj[i+1].slug
                prevobj = Allobj[i-1].slug
           

   
       

    
    return render(request, 'articles/article_detail.html',{'art1':art1,'final':body,'rev':homeurl+rev_url,'next':nextobj,'prev':prevobj})

cats/views.py
from django.shortcuts import render
from articles.models import Cat
# Create your views here.
from django.http import HttpResponse
from django.core.mail import send_mail
from django.contrib import messages


def cat(request, CatHead):
    cat = Cat.objects.get(CatHead=CatHead)
    labels = ['im0','im1','im2','im3','im4','im5','im6','im7','im8','im9']
    c = list()
    d = dict()
    for i in labels:
        b = getattr(cat,i).url
        setts = getattr(cat, i+"_setting")
        head = getattr(cat, i+"_head")
        if(b != "/media/default.png"):

            c.append(b)
            d.update({b:[setts,head]})

    return render(request, 'cats/cats.html',{'cat':cat,'c':c,'d':d})

articles/templates/articles/article_detail.html
{% extends 'base.html' %}

{% block content %}
    
    
    <div class="art1" style="background:  white;width: 100%;">
        <br>
        <!--<img src="{{art1.thumb.url}}" class='img-responsive img-center' style="margin: 0 auto;width:80%; height:80%;" />--> 
        <h1  class='text-center font-fam'>{{art1.title|title}}</h1>
        
        <h3  class="text-center">{{art1.date}}</h3>
        
        <div class='text-center'>
            <a href="https://www.facebook.com/sharer/sharer.php?u={{rev}}" target="_blank"><i class="fa fa-facebook-square"></i></a>
            &nbsp;
            <a href='https://pinterest.com/pin/create/button/?url={{rev}}&description=Check out this cool article'><i class="fa fa-pinterest" style="color:#bd0819;"></i></a>
            &nbsp;
            <a href="https://twitter.com/intent/tweet?hashtags=ApertureMinimusPhotography&text=Check out this cool article at {{rev}}"> <i class="fa fa-twitter" ></i></a>
        </div>
        
        <br>
        <p  >{{final|safe}}</p>
        <br>
        <div class="container-fluid">
        <div class = 'row text-center' >
        <div class = 'col-md-6'><a href= "{% url 'articles:detail' slug=prev %}"><button class="btn btn-primary" style="background-color:black;font-family: 'Oswald';font-size:18px;">Prev</button></a></div>
        <div class='col-md-6'><a href = "{% url 'articles:detail' slug=next %}"><button class="btn btn-primary" style="background-color:black;margin:10px;font-family: 'Oswald';font-size: 18px;">Next</button></a></div>
        </div>
        </div>
    </div>
{% endblock %}

articles/templates/articles/article_list.html
{% extends 'base.html' %}

{% block content %}
    <br>
    <h1 class="text-center font-fam" >Blog</h1> 
    <br>
    <!--TODO:: thumbnail sathi upload kartanna image predef resolution mdhe cut karayachi
        TODO::  thumbnail aathvan thevjo w3 var kuth tari pahla hota aapan example with cards
    -->
    
    <div>
        <div class='container-fluid'>
        <div class='row'>
        {% for i in article %}
           
        <a href="{% url 'articles:detail' slug=i.slug %} " style="color:black" >
            <div class=' col-sm-3 text-center' style="padding:10px;" >
                <span class='border border-primary'>
                <div  id="main-" class = "cc well card card-success" style="" >
                <br>
                <h4 style="color: white;font-family: 'Oswald'">{{i.title}}</h4>
               
                <h5 style="color: white;font-family: 'Roboto Condensed';">{{i.snippet}}</h5>
                <h5 style="color: white;font-family: 'Oswald';">{{i.date}}</h5>
                <br>
                </div>
                </span>
                
              
            </div>
           
        </a>
        {% endfor %}
        </div>
        </div>
    </div>
    
  
{% endblock %}

cats/templates/cats/cats.html
{% extends 'base.html' %}
{% block content %}
    <script>
    
    $( document ).ready(function() {
        $('#myModal').on('show.bs.modal', function (event) {
                var button = $(event.relatedTarget) // Button that triggered the modal
                var recipient = button.data('imurl')
                var tit = button.data('title') // Extract info from data-* attributes
  // If necessary, you could initiate an AJAX request here (and then do the updating in a callback).
  // Update the modal's content. We'll use jQuery here, but you could use a data binding library or other methods instead.
                var modal = $(this)
                var sd = modal.find('.modal-body')
                modal.find('.modal-title').text(tit)
                var set = button.data('setting')
                modal.find('.modal-body').html("<img src='"+recipient+"' class='img-responsive' /><div class='foot-h' style='color:black;'>"+set+"</div>")
                    })
        });
    
    
    </script>
    <div class="container-fluid">
        <div class="row">
                 {% for i,j in d.items %}
                        <div class="col-lg-4" style="padding: 0px;">
                       
                        <img src="{{i}}"  class="img-responsive btn" data-toggle="modal" data-title="{{j.1|safe}}" data-setting="{{j.0}}" data-imurl="{{i}}" data-target="#myModal"  style="padding: 0px;" />
                        </div>
                       

                 {% endfor %}
        </div>
        {% for i in c %}
        <div class="modal fade" id="myModal" role="dialog">
            <div class="modal-dialog modal-lg">
              <div class="modal-content">
                <div class="modal-header">
                  <button type="button" class="close" data-dismiss="modal">&times;</button>
                  <h4 class="modal-title foot-h" style="color: black;" >{{cat.CatHead}}</h4>
                </div>
                <div class="modal-body">
                    <img id="mi" src="#" class="img-responsive" />
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
              </div>
            </div>
          </div>
        {% endfor %}
    </div>

{% endblock %}

templates/base.html
{% load static %}
{% load analytical %}
<!DOCTYPE html>
<html>
<head>
    {% analytical_head_top %}
    <meta charset="utf-8" />
    <!-- Chrome, Firefox OS and Opera -->
  <meta name="theme-color" content="#000000">
<!-- Windows Phone -->
  <meta name="msapplication-navbutton-color" content="#000000">
<!-- iOS Safari -->
  <meta name="apple-mobile-web-app-status-bar-style" content="#000000">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'Gt.png' %}" />
    <title>Aperture Minimus</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/css?family=Roboto+Condensed" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Rubik|Rubik+Mono+One" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Anton" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Viga" rel="stylesheet">


    <link href="https://fonts.googleapis.com/css?family=Luckiest+Guy" rel="stylesheet">

    <link href="https://fonts.googleapis.com/css?family=Oswald|Roboto+Condensed" rel="stylesheet">
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    

    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link rel="stylesheet" type="text/css" media="screen" href="{% static 'base.css' %}" />
    <style> 
      @font-face {
          font-family: 'Arkhip';
         src:  url("{% static 'Arkhip_font.ttf' %}")  format('truetype'); 
      } 
      .text{
        position: absolute;
        top: 40%;
        left: 40%;
      }
      .vis .text {
        visibility: hidden;
      }
      .dis:hover{
        opacity: 0;
      }
      .vis:hover .text {
        visibility: visible;
       
      }
      input{
        border: 0;
        border-bottom: 2px solid black;
        font-family: 'Viga';
        outline: none;
        width: 100%;
      }
      textarea{
        border:0;
        border-bottom: 2px solid black;
        font-family: 'Viga';
        outline: none;
        width: 100%;
        height: 100px;
      }
      .foot-h{
        font-family: 'Oswald';
        color: white;
      }
      .toppad{
            padding-top: 210px;
            padding-left: 50px;
        }
      .foot-t{
        color: white;
        font-family: 'Viga';
        
        margin-left: 30px;
        margin-right: 30px;
      }

      .hor{
        height:2px;
        background: #bababa;
        margin:0 auto;
        margin-top:10px;
        margin-bottom:10px;

      }
      .form-f{
        font-family: 'Oswald';
        color: black;
      }
      .font-fam{
        font-family: 'Arkhip';
        margin-left:10px;
        margin-right:10px;
      }     
      .well{
        background: black;
      }
      .cap{
        font-family: 'Roboto Condensed';
      }
      .navbar-inverse{
    background-color: #000000;
        }
        p {
          font-size:50px;
          font-family: 'Roboto Condensed';
          color:black;
          display: block;
            margin-top: 1em;
            margin-bottom: 1em;
            margin-left: 300px;
            margin-right: 300px;
            text-indent:1em;  
        text-align:justify;
        text-justify:inter-word;
        }
        h1{
          /*font-family: 'Luckiest Guy';*/
          color:#000000;
        }
        h3{
          font-family: 'Oswald';
          color: #000000;
        }
        
        @media screen and (min-width: 601px) {
         p {
            font-size: 21px;
            
          }
          .padder{
            padding: 100px;
            padding-top: 50px;
          }
          
          .foot-h{
            font-size:21px;
          }
          .form-f{
            font-size: 20px;
          }
          .fhome{
            font-size:50px;
          }
          .hor{
            width: 60px;
          }
          .naver-font{
            margin-top:14px;
            margin-left:5px;
          }
          
          

          .fa{
            font-size:48px;
          }
          .fi{
            font-size:35px;
          }
          h1{
            font-size: 45px;
          }
          h3{
            font-size: 30px;
          }
          .sizer{
            width: 900px;
            height: 500px;
          }
          .sizer-por{
            height: 700px;
            width:500px;
          }
         
          .cap{
            font-size:20px;
          }
        }
        
        @media screen and (max-width: 600px) {
          p {
            font-size: 15px;
            margin-left: 25px;
            margin-right: 25px;
          }
          .padder{
            padding: 10px;
            
          }
          .toppad{
            padding-top: 30px;
            padding-bottom: 30px;
          }
          .form-f{
            font-size: 15px;
          }
          .fhome{
            font-size:25px;
          }
          .foot-h{
            font-size:18px;
          }
          
          .hor{
            
            width:30px;
          }
          .naver-logo{
            display: none;
            /*margin-left:15px;*/
          }
          .naver-font{
           /*display: none;*/
           margin-left:10px;
          }
          .fa{
            font-size:33px;
          }
          h1{
            font-size: 25px;
          }
          h3{
            font-size:20px;
          }
          
          .sizer{
            width:100%;
          }
          .sizer-por{
            width:100%;
          }
          .cap{
            font-size:12px;
          }
        }
        </style>
      
      {% analytical_head_bottom %} 
</head>
<body>
    {% analytical_body_top %}
        <nav class="navbar navbar-fixed-top navbar-inverse" >
                <div class="container-fluid">
                  <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                      <span class="icon-bar"></span>
                      <span class="icon-bar"></span>
                      <span class="icon-bar"></span>                        
                    </button>
                    <a class="navbar-left naver-logo" href="{% url 'homeurl' %}"><img src="{% static 'Gt.png' %}"  class="navbar-left"  style="margin-top: 10px;" width=30 height=30/></a>
                    <a class="navbar-left " href="{% url 'homeurl' %}" style="font-family: 'Viga';text-transform: uppercase;color:white;"><h2 style='font-size:20px;' class='naver-font'>ApertureMinimus</h2></a>
                  </div>
                  <div class="collapse navbar-collapse" id="myNavbar">
                    <ul class="nav navbar-nav">
                      <li class="active"><a href="{% url 'homeurl' %}" style="font-family: 'Viga';text-transform: uppercase;color:white;"><b>Home</b></a></li>
                      
                      <li ><a href="{% url 'articles:list'  %}" style="font-family: 'Viga';text-transform: uppercase;color:white;"><b>Blog</b></a></li>
                      <li><a href="{% url 'homeurl' %}#about" style="font-family: 'Viga';text-transform: uppercase;color:white;"><b>About</b></a></li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                     
                      <li><a href="{% url 'homeurl' %}#contact" style="font-family: 'Viga';text-transform: uppercase;color:white;"><b>Contact</b></a></li>
                    </ul>
                  </div>
                </div>
              </nav>
            
   <div style="min-height: 100%;">
     <br>
     <br>
  
    {% block content %}
    
    {% endblock %}
    </div>
    <br>
    <br>
   
   
    <div id = 'footer' class="container-fluid" style="padding: 0px; background: #000000;">
    <div style="height:auto;width:100%;">
      <div class="col-sm-4 " style="padding-top:20px;">
        <div class="text-center"><span class="foot-h ">ApertureMinimus</span><br>
        <div class="hor"></div></div>
        <div class="foot-t "><span class="">An Awesomely Weird Photographer, Cinematographer And Motion Designer From India.</span></div>
        <br>
      </div>
      <div class="col-sm-4 text-center" style="padding-top:20px;">
        <div class="text-center"><span class="foot-h">Social</span><br><div class="hor"></div></div>
        <a href="https://www.quora.com/profile/Harshadeep-Pahurkar"><i class="fa fa-quora fi" style="color:#ffffff;"> </i></a>&nbsp;
        <a href="https://www.facebook.com/Aperture-Minimus-Photography-380065635828110/"><i class="fa fa-facebook-official fi" style="color:#ffffff;" > </i></a>&nbsp;
        <a href="https://www.youtube.com/channel/UCSzV3oKfogk57furA14KrwQ"><i class="fa fa-youtube-play fi" style="color:#ffffff;"></i></a>&nbsp;
        <a href="#"><i class="fa fa-twitter fi" style="color:#ffffff;"></i></a>&nbsp;
        <a href="https://www.instagram.com/the_chhayachitrakaar/"><i class="fa fa-instagram fi" style="color:#ffffff;"></i></a>&nbsp;
        <br>
      </div>
      <div class="col-sm-4 text-center" style="padding-top:20px;">
        <div class="text-center"><span class="foot-h">Contact</span><br><div class="hor"></div></div>
        
        <span class="foot-t"><i class="fa fa-envelope fi" style="color:#ffffff;"></i> &nbsp; &nbsp; Harshadeeppahurkar@gmail.com </span><br>
        <br>
        
      </div>
      
    </div>
    
    </div>
   

    {% analytical_body_bottom %}
</body>
</html>

templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

        
    <div class="container-fluid" style="background: #000000;height: auto;">
        <div class="row">
        <div class=""><div class="col-lg-6" style="background: #000000;"><div  class="toppad" style="background: #000000;"><span style="color: #ffffff;font-family: 'Viga';" class="fhome">Hello;<br></span><span class= 'fhome' style="font-family: 'Viga';color: #ffffff;"> I'M HARSHADEEP PAHURKAR AND I'M A PHOTOGRAPHER. </span></div> </div></div>
        <div class="col-lg-6" style="background: #000000;padding: 0;"><img src="{% static 'homediv.jpg' %}" class="img-responsive" /></div>
        </div>
    </div>
    <br>
    <br>
    <br>
    
    <div  class="container-fluid text-center foot-h" style="color:#000000;">
        <span style="background: #000000; color: #ffffff;padding-left: 10px;padding-right: 10px;">01</span> &nbsp;
        <span>PORTFOLIO</span>
    </div>
    <br>
    
    <div class="container-fluid "  >
        <div class="row padder"  >
                {% for i in Cats %}
                
                <div  data-url= "{{i.Thumb.url}}" class="col-md-4 " style="padding: 2px;" >
                <div class='vis'>
                       <a href= "{% url 'cats:categories' CatHead=i.CatHead  %}" > <img   src = "{{i.Thumb.url}}" class="img-responsive dis" width=500 height=500  /></a>
                        <div class="overlay"><div class="text-center text foot-h"  style="color:#000000;font-size: 20px;">{{i.CatHead}}</div></div>
                </div>
                </div>
                
                {% endfor %}
        </div>
   </div>
    <br>
    
    <br>

    
    <div class="container-fluid text-center foot-h" style="color:#000000;"  id="about" >
            <span  style="background: #000000; color: #ffffff;padding-left: 10px;padding-right: 10px;">02</span> &nbsp;
            <span>ABOUT</span>
    </div>
    <br>
    <br>
    <div  class="text-center"><p style="font-family: 'Viga';"> Hello guys, I Am Harshadeep Pahurkar, I am a Small town photographer and motion designer from India, I have been doing photography, Since 2016, You can check my work and read interesting photography blogs here. You can use the contact form to strike up a conversation with me, I am listening, Let’s talk.</p></div>
    <br>
    <br>
    <br>
    
    <div class="container-fluid text-center foot-h" style="color:#000000;" id="contact">
            <span style="background: #000000; color: #ffffff;padding-left: 10px;padding-right: 10px;">03</span> &nbsp;
            <span>CONTACT</span>
    </div>
    <br>
    <br>
    <br>
    
    <div class="container-fluid" >
    
    <form class=''  action="{% url 'homeurl' %}" method="post">
        {% csrf_token %}
        {{ form.non_field_errors }}
        <div class="row">
        <div class="col-lg-1"></div>
        <div class="col-lg-5">
        <div class="fieldWrapper" style="padding-top:10px;">
                
                {{ form.Name.errors }}
                <label class = 'form-f' style="border: 0; " for="{{ form.Name.id_for_label }}">Name:</label>
                {{ form.Name }}
            </div>
        </div>
        <div class="col-lg-5">
                <div class="fieldWrapper" style="padding-top:10px;">
                       
                        {{ form.sender.errors }}
                        <label class='form-f' style="border: 0;" for="{{ form.sender.id_for_label }}">Email:</label>
                        {{ form.sender }}
                </div>
        </div><br>
        <div class="col-lg-1"></div>
        </div>
        <div class="row">
            <div class="col-lg-1"></div>
            
            <div class="col-lg-10">
                    <div class="fieldWrapper" style="padding-top:10px;">
                       
                            {{ form.subject.errors }}
                            <label class="form-f" style="border: 0;" for="{{ form.subject.id_for_label }}">Subject:</label>
                            {{ form.subject }}
                    </div>
            </div>
        </div>
        <div class="row">
                <div class="col-lg-1"></div>
                <div class="col-lg-10">
                <div class="fieldWrapper" style="padding-top:10px;">
                              
                        {{ form.message.errors }}
                        <label class="form-f" style="border: 0;" for="{{ form.message.id_for_label }}">Message:</label>
                        {{ form.message }}
                </div>
                </div>
        </div>
        <br>
        <div class="text-center"><input class = 'btn text-center ' style="background-color:black;font-family: 'Oswald';font-size:18px; width: auto;color: #ffffff;" type="submit" value="Send" /></div>
    </form>
    <br>
   
    </div>
    <div id = 'message' class="container">
        {% for message in messages %}
           
        <div class="alert alert-success text-center">{{message}}</div> 
        
        {% endfor %}
    </div>        
    
     
     
    

{% endblock %}
    